version: '2'
services:
    monolithicappwithoutregistry-app:
        image: tanjie123/monolithicappwithoutregistry
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monolithicappwithoutregistry-mysql:3306/monolithicappwithoutregistry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolithicappwithoutregistry-mysql:
        extends:
            file: mysql.yml
            service: monolithicappwithoutregistry-mysql
