apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monolithicappwithoutregistry-app
  namespace: default
  labels:
    team: default
spec:
  selector:
    matchLabels:
      app: monolithicappwithoutregistry
  endpoints:
  - port: web
    path: /prometheusMetrics
